[[repos]]
url = "https://raw.githubusercontent.com/leftwm/leftwm-community-themes/master/known.toml"
name = "community"
definitions_version = 0

[[repos.themes]]
name = "Orange Forest"
directory = "/home/i0xfce/.config/leftwm/themes/Orange Forest"
repository = "https://github.com/PVautour/leftwm-theme-orange-forest/"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
current = false

[[repos.themes]]
name = "Coffee"
directory = "/home/i0xfce/.config/leftwm/themes/Coffee"
repository = "https://github.com/lex148/leftwm-coffee/"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
current = false

[[repos.themes]]
name = "Soothe"
repository = "https://github.com/b4skyx/leftwm-soothe/"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
current = false
relative_directory = "theme/"

[[repos.themes]]
name = "TNG"
repository = "https://github.com/lex148/leftwm-tng/"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
current = false

[[repos.themes]]
name = "Windows XP"
repository = "https://github.com/lex148/leftwm-windowsxp/"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
current = false

[[repos.themes]]
name = "Dracula Rounded"
repository = "https://github.com/AethanFoot/leftwm-theme-dracula-rounded/"
commit = "*"
version = "0.0.2"
leftwm_versions = "^0.2.7, <0.3.0"
current = false

[[repos.themes]]
name = "Forest"
repository = "https://github.com/lex148/forest/"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
current = false

[[repos.themes]]
name = "Ground Zero"
directory = "/home/i0xfce/.config/leftwm/themes/Ground Zero"
repository = "https://github.com/Qwart376/Ground-Zero/"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
current = false

[[repos.themes]]
name = "Red Moon"
directory = "/home/i0xfce/.config/leftwm/themes/Red Moon"
repository = "https://github.com/Qwart376/Red-Moon"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
current = false

[[repos.themes]]
name = "Blue Coffee"
directory = "/home/i0xfce/.config/leftwm/themes/Blue Coffee"
repository = "https://github.com/Qwart376/Blue-Coffee/"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
current = false

[[repos.themes]]
name = "sunflower"
repository = "https://github.com/mautamu/leftwm-sunflower/"
commit = "*"
version = "0.1.2"
leftwm_versions = "^0.2.11, <0.3.0"
current = false

[[repos.themes]]
name = "Bumblebee"
directory = "/home/i0xfce/.config/leftwm/themes/Bumblebee"
repository = "https://github.com/mfdorst/leftwm-bumblebee/"
commit = "*"
version = "0.0.1"
leftwm_versions = "^0.2.8, <0.3.0"
current = false

[[repos.themes]]
name = "Changed Sunset"
repository = "https://github.com/Syudagye/changed-sunset"
commit = "*"
version = "0.0.1"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "Garden"
repository = "https://github.com/taylor85345/leftwm-theme-garden"
commit = "*"
version = "0.0.4"
leftwm_versions = ">0.2.7"
current = false

[[repos.themes]]
name = "Epitaph"
repository = "https://github.com/VentGrey/Epitaph"
commit = "*"
version = "0.0.1"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "Ocean-night"
repository = "https://github.com/TheRoniOne/ocean-night"
commit = "*"
version = "0.0.1"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "Flamingo"
directory = "/home/i0xfce/.config/leftwm/themes/Flamingo"
repository = "https://github.com/necaris/leftwm-theme-flamingo"
commit = "*"
version = "0.0.1"
leftwm_versions = ">0.2.7, <0.3.0"
current = false

[[repos.themes]]
name = "Sunset"
directory = "/home/i0xfce/.config/leftwm/themes/Sunset"
repository = "https://github.com/Syudagye/leftwm-sunset"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
current = false

[[repos.themes]]
name = "Amber"
repository = "https://github.com/di-effe/amber"
commit = "*"
version = "0.2.2"
leftwm_versions = ">0.2.10, <0.3.0"
current = false

[[repos.themes]]
name = "Catppuccin"
repository = "https://github.com/di-effe/catppuccin"
commit = "*"
version = "0.1.1"
leftwm_versions = ">0.2.10, <0.3.0"
current = false

[[repos.themes]]
name = "Molese"
directory = "/home/i0xfce/.config/leftwm/themes/Molese"
repository = "https://github.com/m0lese/leftwm-config"
commit = "*"
version = "2.1.0"
leftwm_versions = ">0.2.10, <0.3.0"
current = false

[[repos.themes]]
name = "Double Bar"
repository = "https://github.com/PeterDauwe/doublebar/"
commit = "*"
version = "0.0.1"
leftwm_versions = "<0.3.0"
current = false

[[repos.themes]]
name = "SpaceJelly"
repository = "https://gitlab.com/jchand99/space_jelly"
commit = "*"
version = "1.0.0"
leftwm_versions = ">0.2.10, <0.3.0"
current = false

[[repos.themes]]
name = "Ascent"
repository = "https://gitlab.com/mWalrus/ascent"
commit = "*"
version = "1.0.0"
leftwm_versions = ">0.2.7"
current = false

[[repos]]
url = "localhost"
name = "LOCAL"
definitions_version = 0

[[repos.themes]]
name = "candy"
directory = "/home/i_0xfce/.config/leftwm/themes/candy"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "polybar-spotify"
directory = "/home/i_0xfce/.config/leftwm/themes/polybar-spotify"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "purplaxer-dev"
directory = "/home/i_0xfce/.config/leftwm/themes/purplaxer-dev"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "db-color-dev (back up 1)"
directory = "/home/i_0xfce/.config/leftwm/themes/db-color-dev (back up 1)"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "purplax"
directory = "/home/i_0xfce/.config/leftwm/themes/purplax"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "0xfce"
directory = "/home/i0xfce/.config/leftwm/themes/0xfce"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "Bluepax"
directory = "/home/i0xfce/.config/leftwm/themes/Bluepax"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "Bluepax - Phase 3"
directory = "/home/i0xfce/.config/leftwm/themes/Bluepax - Phase 3"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "Bluepax - Phase 2"
directory = "/home/i0xfce/.config/leftwm/themes/Bluepax - Phase 2"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "Bluepax2"
directory = "/home/i0xfce/.config/leftwm/themes/Bluepax2"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "Bluepax3"
directory = "/home/i0xfce/.config/leftwm/themes/Bluepax3"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "leftwm-community-themes"
directory = "/home/i0xfce/.config/leftwm/themes/leftwm-community-themes"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "tng"
directory = "/home/i0xfce/.config/leftwm/themes/tng"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "windowsxp"
directory = "/home/i0xfce/.config/leftwm/themes/windowsxp"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "screenshots"
directory = "/home/i0xfce/.config/leftwm/themes/screenshots"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "dracula-rounded"
directory = "/home/i0xfce/.config/leftwm/themes/dracula-rounded"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "orangeforest"
directory = "/home/i0xfce/.config/leftwm/themes/orangeforest"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "leftwm-theme-garden"
directory = "/home/i0xfce/.config/leftwm/themes/leftwm-theme-garden"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "epitaph"
directory = "/home/i0xfce/.config/leftwm/themes/epitaph"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "catppuccin"
directory = "/home/i0xfce/.config/leftwm/themes/catppuccin"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "space_jelly"
directory = "/home/i0xfce/.config/leftwm/themes/space_jelly"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "soothe"
directory = "/home/i0xfce/.config/leftwm/themes/soothe"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "leftwm-sunflower"
directory = "/home/i0xfce/.config/leftwm/themes/leftwm-sunflower"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "amber"
directory = "/home/i0xfce/.config/leftwm/themes/amber"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "coffee"
directory = "/home/i0xfce/.config/leftwm/themes/coffee"
version = "0.0.0"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "Bluepex"
directory = "/home/i0xfce/.config/leftwm/themes/Bluepex"
version = "0.0.0"
leftwm_versions = "*"
current = true

[[repos]]
url = "https://raw.githubusercontent.com/arcolinux/arcolinux-leftwm-themes/master/known.toml"
name = "arcolinux"
definitions_version = 0

[[repos.themes]]
name = "docky"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-docky/"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "eden"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-eden/"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "material"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-material/"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "mesh"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-mesh/"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "matrix"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-matrix/"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "parker"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-parker/"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "pi"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-pi/"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "shades"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-shades/"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "space"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-space/"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "starwars"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-starwars/"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "smooth"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-smooth/"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "forest"
directory = "/home/i0xfce/.config/leftwm/themes/forest"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-forest/"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "grayblocks"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-grayblocks/"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "greyblocks"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-greyblocks/"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "halo"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-halo/"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "db"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-db/"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "db-scifi-star"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-db-scifi-star/"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "db-nemesis"
directory = "/home/i0xfce/.config/leftwm/themes/db-nemesis"
repository = "https://github.com/arcolinux/arcolinux-leftwm-theme-db-nemesis/"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos]]
url = "https://raw.githubusercontent.com/arcolinux/arcolinux-leftwm-themes-community/main/known.toml"
name = "arcolinux-community"
definitions_version = 0

[[repos.themes]]
name = "doublebar"
directory = "/home/i0xfce/.config/leftwm/themes/doublebar"
repository = "https://github.com/PeterDauwe/doublebar/"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "db-color-dev"
repository = "https://github.com/PeterDauwe/db-color-dev"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "db-scifi"
repository = "https://github.com/PeterDauwe/db-scifi"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "db-labels"
repository = "https://github.com/PeterDauwe/db-labels"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "db-comic"
repository = "https://github.com/PeterDauwe/db-comic"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false

[[repos.themes]]
name = "sb-horror"
repository = "https://github.com/PeterDauwe/sb-horror"
commit = "*"
version = "2.3.2"
leftwm_versions = "*"
current = false
